package game

import (
	"fmt"
	"slices"
	"strings"

	"github.com/google/uuid"
)

// prevent_next_from_source.go — ADR 0107 §6 (#1860): the shield against
// "the next time a source would deal damage", the choice of that source,
// and what the shield does with the damage it prevented.
//
// THE RULES.
//
//   - CR 615.8: "Some prevention effects generated by the resolution of a
//     spell or ability refer to the next time a specific source would deal
//     damage. These effects prevent the next instance of damage from that
//     source, regardless of how much damage that is."
//   - CR 615.9 / 609.7b: a shield against "a source of a player's choice
//     with certain properties" rechecks the properties when the source
//     would deal damage. If they no longer match, the damage isn't
//     prevented and the shield isn't used up.
//   - CR 609.7a: the player may choose a permanent, a spell on the stack,
//     any object referred to by an object on the stack, by a replacement
//     or prevention effect waiting to apply or by a delayed trigger
//     waiting to trigger (even if it has left the zone it was in), or a
//     face-up object in the command zone. "The source is chosen when the
//     effect is created." A chosen permanent spell covers the permanent it
//     becomes as well.
//   - CR 615.5: the additional effect of a prevention effect may refer to
//     the amount prevented, and takes place immediately afterward.
//
// THE SHAPE (ADR 0107 §6 decision 1). One scoped replacement kind,
// ModPreventNextFromSource, plain data in a ScopedEffect record, so a
// table holding one is a restore point. Its mod names:
//
//   - the source, Objects[0] (an ObjectRef: the instance and the epoch it
//     had when it was chosen, CR 400.7), with SourceZone saying where it
//     was. No Objects means "a source with these properties" and no
//     choice at all (Circle of Solace's "the next time a creature of the
//     chosen type would deal damage to you").
//   - the protected player (Player), optionally with the permanents of
//     some types that player controls (Types: Shadowbane's "you and/or
//     creatures you control"); or a pinned permanent (the record's
//     Affected set); or nothing ("would deal damage this turn").
//   - the CR 615.9 recheck, Queries (any of them), read against the
//     source's last-known information as the damage is dealt.
//   - the follow-up, Then: a registered body key, run with the amount
//     prevented (CR 615.5).
//
// THE NEXT INSTANCE, NOT THE NEXT EVENT. The engine opens one damage
// event per recipient, so a source dealing damage to several things at
// once — an attacker with trample, a creature blocked by two, a spell
// that deals damage to each creature — is several events and ONE
// instance (CR 615.8). The shield is therefore marked spent with the
// damage instance it was used in (Mod.SpentInstance, ADR 0108 PR 0,
// damage_instance.go) and keeps applying to that instance's other events
// and to nothing else. It also records the event batch (Mod.SpentBatch),
// which is what drops the spent record when play moves on
// (beginEventBatchLocked). Its follow-up is owed for the instance as a
// whole and runs once, with the total, as the instance ends
// (PreventionFollowUp).
//
// ADR 0107 §6 used the batch as the instance, and the batch is wider: two
// separate instances of damage from the same source inside one resolution
// ("it deals 2 damage to you. Then it deals 2 damage to you") were one
// batch, and a shield prevented both. ADR 0108 PR 0 fixed that known
// limit with the instance. A record written before it carries SpentBatch
// alone and still applies for the rest of that batch.

// ModPreventNextFromSource is "the next time <source> would deal damage
// [to <protected>] this turn, prevent that damage" (CR 615.8). Reads
// Objects, SourceZone, Queries, Player, Types, Then, CombatOnly, SpentBatch
// and SpentInstance. Scope
// ScopeGame for a protected player or none; pinned (ScopeNone) to the
// protected permanent.
const ModPreventNextFromSource ModKind = "preventNextFromSource"

// NextDamageShield is the queue-side description of a
// ModPreventNextFromSource record.
type NextDamageShield struct {
	// EffectSource is the card whose spell or ability made the shield —
	// the record's Source, and the source of any follow-up damage
	// ("Deflecting Palm deals that much damage").
	EffectSource uuid.UUID
	// Controller is "you": the shield's controller and the follow-up's.
	Controller uuid.UUID

	// Source is the chosen source; the zero ref is "any source matching
	// Queries" (Circle of Solace). Built with DamageSourceRefLocked.
	Source     ObjectRef
	SourceZone ZoneKind

	// Queries is the CR 615.9 recheck: the source must match one of them
	// when it would deal damage. Empty is no recheck.
	Queries []PermanentQuery

	// ProtectPlayer is the protected player; ProtectTypes adds the
	// permanents of those (lowercase) types that player controls
	// ("you and/or creatures you control"). ProtectPermanent is a
	// protected permanent instead. All zero protects everything.
	ProtectPlayer    uuid.UUID
	ProtectTypes     []string
	ProtectPermanent uuid.UUID

	// Then is the CR 615.5 follow-up, run with the amount prevented.
	// Zero is none.
	Then BodyRef

	// CombatOnly is "the next time <source> would deal COMBAT damage"
	// (Impulsive Maneuvers' losing flip, ADR 0108 §3): non-combat damage
	// from the source neither meets the shield nor spends it.
	CombatOnly bool

	// Label is the record's label, shown in a CR 616 ordering prompt.
	Label string
}

// PreventNextDamageFromSourceForEffect registers the shield for the rest
// of the turn (every printed card says "this turn"; CR 514.2 ends it).
// Reports whether a record was written: nothing is registered for a
// shield that names neither a source nor a property, or a protected
// permanent that is not on the battlefield.
//
// Caller must hold g.mu (write) — every caller is a resolving effect.
func (g *Game) PreventNextDamageFromSourceForEffect(s NextDamageShield) bool {
	if s.Source.ID == uuid.Nil && len(s.Queries) == 0 {
		return false
	}
	m := Mod{
		Kind:       ModPreventNextFromSource,
		SourceZone: s.SourceZone,
		Queries:    clonePermanentQueries(s.Queries),
		Player:     s.ProtectPlayer,
		Types:      copyStrings(s.ProtectTypes),
		Then:       s.Then.key,
		CombatOnly: s.CombatOnly,
	}
	if s.Source.ID != uuid.Nil {
		m.Objects = []ObjectRef{s.Source}
	}
	label := s.Label
	if label == "" {
		label = "prevent the next damage from a source"
	}
	d := g.UntilEndOfTurnDuration()
	if s.ProtectPermanent != uuid.Nil {
		affected := g.PinnedObjectsLocked(s.ProtectPermanent)
		if len(affected) == 0 {
			return false
		}
		return g.appendScopedEffectLocked(s.EffectSource, affected, ScopeNone, s.Controller, []Mod{m},
			g.PinnedTo(d, s.ProtectPermanent), label, timeNowUnixNano())
	}
	return g.RegisterScopedRuleEffectForEffect(s.EffectSource, ScopeGame, s.Controller, []Mod{m}, d, label)
}

// DamageSourceRefLocked pins the object `id` names right now as a damage
// source (CR 400.7): its instance, its epoch and its zone. ok is false
// for an ID in no zone.
//
// Caller must hold g.mu.
func (g *Game) DamageSourceRefLocked(id uuid.UUID) (ObjectRef, ZoneKind, bool) {
	z := g.findCardZoneLocked(id)
	if z == nil {
		return ObjectRef{}, "", false
	}
	return ObjectRef{ID: id, Epoch: g.cardObjectEpochLocked(id)}, z.Kind, true
}

func clonePermanentQueries(qs []PermanentQuery) []PermanentQuery {
	if len(qs) == 0 {
		return nil
	}
	out := make([]PermanentQuery, len(qs))
	for i, q := range qs {
		out[i] = PermanentQuery{
			Types:      copyStrings(q.Types),
			Subtypes:   copyStrings(q.Subtypes),
			Supertypes: copyStrings(q.Supertypes),
			Colors:     copyStrings(q.Colors),
			Keyword:    q.Keyword,
			Enchanted:  q.Enchanted,
		}
	}
	return out
}

// nextFromSourceModProblem is registration's (and restore's) check on the
// kind's parameters.
func nextFromSourceModProblem(m Mod) string {
	if m.Kind != ModPreventNextFromSource {
		// #1879: the granted "can't attack unless defending player
		// controls" reads Queries too, as what the defender must control.
		queries := len(m.Queries) != 0 && m.Kind != ModCantAttackUnlessDefenderControls
		// ADR 0108 §3: a multiplier names its one source and its "next
		// time" spend with the same fields (multiplyDamageModProblem
		// checks it).
		sourced := m.SourceZone != "" || m.SpentBatch != 0 || m.SpentInstance != 0
		if m.Kind == ModMultiplyDamage {
			sourced = false
		}
		if sourced || queries {
			return fmt.Sprintf("mod %q carries a damage-source field only preventNextFromSource reads", m.Kind)
		}
		return ""
	}
	if len(m.Objects) > 1 {
		return "a preventNextFromSource shield names more than one source"
	}
	if len(m.Objects) == 0 && len(m.Queries) == 0 {
		return "a preventNextFromSource shield names neither a source nor a property"
	}
	if len(m.Objects) == 1 && m.Objects[0].ID == uuid.Nil {
		return "a preventNextFromSource shield names an empty source"
	}
	for _, q := range m.Queries {
		if q.Enchanted {
			return "a preventNextFromSource recheck cannot ask whether a source is enchanted"
		}
	}
	if m.Then != "" && !KnownEffectBody(m.Then) {
		return fmt.Sprintf("preventNextFromSource names follow-up body %q, which is not registered", m.Then)
	}
	return ""
}

// nextFromSourceAppliesLocked is the kind's AppliesTo.
//
// Caller must hold g.mu.
func (g *Game) nextFromSourceAppliesLocked(e ScopedEffect, m Mod, ev *ReplacementEvent) bool {
	if ev.Kind != RepEventDamage || ev.DamageAmount <= 0 {
		return false
	}
	// "The next time it would deal combat damage": other damage passes
	// the shield by, unspent.
	if m.CombatOnly && !ev.IsCombatDamage {
		return false
	}
	// Spent in an earlier instance: CR 615.8's "any subsequent instances
	// … are dealt normally".
	if !nextShieldOpenToLocked(g, m, ev) {
		return false
	}
	if len(m.Objects) == 1 && !g.damageFromChosenSourceLocked(m, ev.DamageSource) {
		return false
	}
	// CR 615.9 / 609.7b: the properties are rechecked as the damage would
	// be dealt, against the source as it is then (its last-known
	// information once it has gone). A shield whose source fails the
	// recheck does not apply, and so is not used up.
	if len(m.Queries) > 0 && !queriesMatchCharacteristic(m.Queries, ev.SourceLKI) {
		return false
	}
	return g.nextFromSourceProtectsLocked(e, m, ev.DamageTarget)
}

// damageFromChosenSourceLocked reports whether the damage source `id` is
// the object the shield chose (CR 400.7):
//
//   - the same object: the instance, still at the epoch it had;
//   - a permanent spell that has since resolved into a permanent, "any
//     damage dealt by the permanent that spell becomes" (CR 609.7a): one
//     zone change, and the card is on the battlefield now;
//   - a chosen permanent that has since left the battlefield, dealing
//     damage as it last existed there ("when this creature dies, it deals
//     2 damage"): one zone change, and the card is not on the battlefield
//     (the same reading departedDamageSourceLocked makes of the source);
//   - a token that has ceased to exist (CR 704.5d) and so is in no zone:
//     it cannot have come back as a new object (CR 111.8).
//
// Caller must hold g.mu.
func (g *Game) damageFromChosenSourceLocked(m Mod, id uuid.UUID) bool {
	ref := m.Objects[0]
	if id == uuid.Nil || id != ref.ID {
		return false
	}
	now := g.cardObjectEpochLocked(id)
	switch {
	case now == ref.Epoch, now == -1:
		return true
	case now == ref.Epoch+1:
		onBattlefield := findBattlefieldCard(g, id) != nil
		switch m.SourceZone {
		case ZoneStack:
			return onBattlefield
		case ZoneBattlefield:
			return !onBattlefield
		}
	}
	return false
}

// nextFromSourceProtectsLocked reports whether damage to `target` is
// damage the shield protects: the protected player, a permanent of a
// named type that player controls, the pinned permanent, or anything at
// all when nothing is named.
//
// Caller must hold g.mu.
func (g *Game) nextFromSourceProtectsLocked(e ScopedEffect, m Mod, target uuid.UUID) bool {
	if e.Scope != ScopeGame {
		return scopedAffectsLiveObjectLocked(g, e, target)
	}
	if m.Player == uuid.Nil {
		return true
	}
	if target == m.Player {
		return true
	}
	if len(m.Types) == 0 {
		return false
	}
	c := findBattlefieldCard(g, target)
	return c != nil && c.Controller == m.Player && slices.ContainsFunc(m.Types, c.HasCardType)
}

// applyNextFromSourceLocked is the kind's Replace: the whole event is
// prevented (CR 615.8, "regardless of how much damage that is"), the
// shield is marked spent for this instance, and the amount is added to
// the follow-up owed for the instance, which runs once with the total
// when the instance has settled (CR 615.5).
//
// Caller must hold g.mu (write).
func (g *Game) applyNextFromSourceLocked(e ScopedEffect, mod int, m Mod, ev *ReplacementEvent) {
	prevented := ev.DamageAmount
	ev.Cancel()
	if m.SpentBatch == 0 && m.SpentInstance == 0 {
		g.markNextShieldSpentLocked(e.Seq, mod, g.currentEventBatchLocked(), ev.DamageInstance)
	}
	g.queuePreventionFollowUpLocked(e, m, ev, prevented)
}

// nextShieldOpenToLocked reports whether a next-damage shield may still
// apply to `ev`: it is unspent, or it was spent by ev's own instance of
// damage (CR 615.8). A record spent before SpentInstance existed — or by
// an event built without a stamp — names only its batch, and is open for
// the rest of that batch, as ADR 0107 §6 read it.
//
// Caller must hold g.mu.
func nextShieldOpenToLocked(g *Game, m Mod, ev *ReplacementEvent) bool {
	switch {
	case m.SpentInstance != 0:
		return ev.DamageInstance == m.SpentInstance
	case m.SpentBatch != 0:
		return m.SpentBatch == g.eventBatch
	}
	return true
}

// markNextShieldSpentLocked records the instance (and the batch) a shield
// was used in. COPY ON WRITE, setShieldChargeLocked's rule: a clone taken
// before the damage shares the slice and must keep the unspent shield, so
// an undo rewinds it.
//
// Caller must hold g.mu (write).
func (g *Game) markNextShieldSpentLocked(seq int64, mod int, batch uint64, inst DamageInstance) {
	i, ok := g.scopedEffectIndexBySeqLocked(seq)
	if !ok {
		return
	}
	next := cloneScopedEffects(g.ScopedEffects)
	rec := next[i]
	rec.Mods = cloneMods(rec.Mods)
	rec.Mods[mod].SpentBatch = batch
	rec.Mods[mod].SpentInstance = inst
	next[i] = rec
	g.ScopedEffects = next
}

// dropSpentNextShieldsLocked removes the shields spent in an earlier
// batch: play has moved on, so the instance they prevented is over (an
// instance never outlives its batch). Called as a new batch begins. Same
// fresh-slice rule as every sweep.
//
// Caller must hold g.mu (write).
func (g *Game) dropSpentNextShieldsLocked() {
	stale := func(e ScopedEffect) bool {
		for _, m := range e.Mods {
			// ADR 0108 §3: a spent "next time" multiplier is done too.
			if spentNextTimeMod(m, g.eventBatch) {
				return true
			}
		}
		return false
	}
	if !slices.ContainsFunc(g.ScopedEffects, stale) {
		return
	}
	kept := make([]ScopedEffect, 0, len(g.ScopedEffects))
	for _, e := range g.ScopedEffects {
		if !stale(e) {
			kept = append(kept, e)
		}
	}
	if len(kept) == 0 {
		kept = nil
	}
	g.ScopedEffects = kept
}

// queriesMatchCharacteristic reports whether a source's characteristics
// match any of the queries. A source the engine cannot see (no last-known
// information) matches none: the shield does not apply, which is the
// weaker direction.
func queriesMatchCharacteristic(qs []PermanentQuery, ch *Characteristic) bool {
	if ch == nil {
		return false
	}
	for _, q := range qs {
		if q.matchesCharacteristic(ch) {
			return true
		}
	}
	return false
}

// matchesCharacteristic is matchesLocked over a characteristics snapshot
// rather than a live permanent — a spell on the stack, or a source as it
// last existed (CR 608.2h). Enchanted is a fact about the battlefield and
// never matches here.
func (q PermanentQuery) matchesCharacteristic(ch *Characteristic) bool {
	if ch == nil || q.Enchanted {
		return false
	}
	fold := func(have []string) func(string) bool {
		return func(want string) bool {
			return slices.ContainsFunc(have, func(h string) bool { return strings.EqualFold(h, want) })
		}
	}
	if len(q.Types) > 0 && !slices.ContainsFunc(q.Types, fold(ch.Types)) {
		return false
	}
	if len(q.Subtypes) > 0 && !ch.AllCreatureTypes && !slices.ContainsFunc(q.Subtypes, fold(ch.Subtypes)) {
		return false
	}
	for _, s := range q.Supertypes {
		if !fold(ch.Supertypes)(s) {
			return false
		}
	}
	if len(q.Colors) > 0 && !slices.ContainsFunc(q.Colors, fold(ch.Colors)) {
		return false
	}
	if q.Keyword != "" && !slices.Contains(ch.Abilities, q.Keyword) {
		return false
	}
	return true
}

// --- the follow-up (CR 615.5) ----------------------------------------

// EventDamagePrevented is the kind of the TriggerContext a prevention
// follow-up body is handed: Source is the damage source, Target what it
// would have been dealt to, Amount how much was prevented, Actor the
// source's controller and Colors the source's colours, all as they were
// when the damage would have been dealt. It is never emitted: CR 615.13's
// "whenever damage is prevented" triggers are not modelled, and no card
// in the catalog prints one.
const EventDamagePrevented EventKind = "damage_prevented"

// PreventionFollowUp is one shield's CR 615.5 additional effect, owed for
// the instance of damage it prevented and not yet run.
//
// ONE PER INSTANCE, NOT PER EVENT. "The damage prevented this way" is the
// total the shield prevented from that one instance — and the engine
// opens one damage event per recipient, so a trampler's split damage, a
// double block or an "each creature" spell is several events. Each event
// the shield prevents adds to the one entry for (Seq, Instance), and the
// body runs ONCE with the total when the instance has settled
// (flushPreventionFollowUpsForInstanceLocked, and ADR 0107's flush
// points): Awe Strike against a 5-power trampler blocked by two gains 5
// life in one event, not 3 and then 2 (which would trigger "whenever you
// gain life" twice). Two instances are two entries (ADR 0108 PR 0): a
// shield applied to two separate instructions' unpreventable damage
// (CR 615.12) runs its follow-up once for each.
//
// Plain data on the Game, carried by the snapshot (a combat damage step's
// instance is owed until a player would next receive priority), rewound
// by undo with the records.
type PreventionFollowUp struct {
	// Seq is the shield record's; Batch the event batch of its instance.
	Seq   int64  `json:"seq"`
	Batch uint64 `json:"batch"`
	// Instance is the damage instance it is owed for (ADR 0108 PR 0,
	// damage_instance.go). Zero on an entry written before it existed,
	// which is grouped by Batch as it was.
	Instance DamageInstance `json:"instance,omitempty"`
	// Body is the shield's Then: a registered body key.
	Body string `json:"body"`
	// Controller is the shield's controller ("you"); Source the card
	// whose effect made the shield; Label the record's.
	Controller uuid.UUID `json:"controller"`
	Source     uuid.UUID `json:"source"`
	Label      string    `json:"label,omitempty"`
	// Prevented is the total prevented so far. Zero is a real total: a
	// shield applied only to damage that can't be prevented (CR 615.12).
	Prevented int `json:"prevented,omitempty"`
	// DamageSource is the source whose damage was prevented, and
	// SourceController / SourceColors are that source as it was when the
	// damage would have been dealt (its last-known information). Target
	// is the first thing it would have been dealt to; Combat says whether
	// it was combat damage.
	DamageSource     uuid.UUID `json:"damageSource"`
	SourceController uuid.UUID `json:"sourceController,omitempty"`
	SourceColors     []string  `json:"sourceColors,omitempty"`
	Target           uuid.UUID `json:"target,omitempty"`
	Combat           bool      `json:"combat,omitempty"`
}

// queuePreventionFollowUpLocked adds `prevented` to the record's
// follow-up for this instance, opening one if it has none. Zero is a real
// amount: CR 615.12's prevention effect applied to damage that can't be
// prevented still has its additional effects, with nothing prevented —
// and still only once for the instance.
//
// COPY ON WRITE, for the reason every registry here is: an undo clone
// shares the slice.
//
// Caller must hold g.mu (write).
func (g *Game) queuePreventionFollowUpLocked(e ScopedEffect, m Mod, ev *ReplacementEvent, prevented int) {
	if m.Then == "" || ev == nil {
		return
	}
	batch := g.currentEventBatchLocked()
	inst := ev.DamageInstance
	next := append([]PreventionFollowUp(nil), g.preventionFollowUps...)
	for i := range next {
		if next[i].Seq == e.Seq && next[i].Instance == inst && (inst != 0 || next[i].Batch == batch) {
			next[i].Prevented += prevented
			g.preventionFollowUps = next
			return
		}
	}
	f := PreventionFollowUp{
		Seq:          e.Seq,
		Batch:        batch,
		Instance:     inst,
		Body:         m.Then,
		Controller:   e.Controller,
		Source:       e.Source.ID,
		Label:        e.Label,
		Prevented:    prevented,
		DamageSource: ev.DamageSource,
		Target:       ev.DamageTarget,
		Combat:       ev.IsCombatDamage,
	}
	if lki := ev.SourceLKI; lki != nil {
		f.SourceController = lki.Controller
		f.SourceColors = copyStrings(lki.Colors)
	}
	g.preventionFollowUps = append(next, f)
}

// flushPreventionFollowUpsLocked runs every owed follow-up once, with its
// total, in the order the shields first applied, and clears them.
//
// WHEN. Once the instance of damage is over. An instruction's instance
// runs its own as it ends (flushPreventionFollowUpsForInstanceLocked, ADR
// 0108 PR 0). This is the catch-all behind it, ADR 0107's two points: as
// a player would next receive priority (runStateChecksLocked, before the
// state-based actions, so a combat damage step's damage is all dealt —
// CR 510.2 — and nothing has died of it yet), and as play moves on to a
// new event batch (beginEventBatchLocked), whichever comes first. A
// follow-up's own damage can meet another shield with a follow-up, so the
// flush repeats, bounded, until nothing is owed.
//
// Caller must hold g.mu (write).
func (g *Game) flushPreventionFollowUpsLocked() {
	for round := 0; round < 8 && len(g.preventionFollowUps) > 0; round++ {
		pending := g.preventionFollowUps
		g.preventionFollowUps = nil
		for _, f := range pending {
			g.runPreventionFollowUpLocked(f)
		}
	}
}

// flushPreventionFollowUpsForInstanceLocked runs the follow-ups owed for
// one instance of damage, as it ends (CR 615.5: "immediately afterward"),
// and leaves every other entry owed. A follow-up's own damage is a new
// instance, which runs its own as it ends.
//
// Caller must hold g.mu (write).
func (g *Game) flushPreventionFollowUpsForInstanceLocked(inst DamageInstance) {
	due := func(f PreventionFollowUp) bool { return f.Instance == inst }
	if inst == 0 || !slices.ContainsFunc(g.preventionFollowUps, due) {
		return
	}
	var run, kept []PreventionFollowUp
	for _, f := range g.preventionFollowUps {
		if due(f) {
			run = append(run, f)
		} else {
			kept = append(kept, f)
		}
	}
	g.preventionFollowUps = kept
	for _, f := range run {
		g.runPreventionFollowUpLocked(f)
	}
}

// runPreventionFollowUpLocked runs one follow-up body. It is the rest of
// its own effect, so an error is logged and the next still runs.
//
// The body is handed an item the engine builds: Controller "you",
// SourceCardID the card that made the shield, and a TriggerContext whose
// event is the prevented damage (EventDamagePrevented); the params carry
// the total (Amount) and the damage source's controller (Player).
//
// Caller must hold g.mu (write).
func (g *Game) runPreventionFollowUpLocked(f PreventionFollowUp) {
	fn, ok := lookupBody(f.Body)
	if !ok {
		effectKeyFault(fmt.Sprintf("game: prevention follow-up body %q is not registered", f.Body))
		return
	}
	trig := Event{
		Kind:   EventDamagePrevented,
		Source: f.DamageSource,
		Target: f.Target,
		Amount: f.Prevented,
		Actor:  f.SourceController,
		Colors: copyStrings(f.SourceColors),
		Combat: f.Combat,
	}
	item := &StackItem{
		ID:           uuid.New(),
		Kind:         StackItemTriggered,
		Controller:   f.Controller,
		Owner:        f.Controller,
		SourceCardID: f.Source,
		Label:        f.Label,
		Trigger:      &TriggerContext{Event: trig},
	}
	p := EffectParams{Amount: f.Prevented, Player: f.SourceController, Object: ObjectRef{ID: f.DamageSource}}
	if err := fn(g, item, p); err != nil {
		g.EmitEvent(Event{
			Kind:     EventEffectError,
			Actor:    f.Controller,
			Source:   f.Source,
			ErrorMsg: "prevention follow-up: " + err.Error(),
		})
	}
}

// clonePreventionFollowUps deep-copies the owed list for a snapshot.
func clonePreventionFollowUps(in []PreventionFollowUp) []PreventionFollowUp {
	if len(in) == 0 {
		return nil
	}
	out := make([]PreventionFollowUp, len(in))
	for i, f := range in {
		f.SourceColors = copyStrings(f.SourceColors)
		out[i] = f
	}
	return out
}

// preventionFollowUpForUnpreventableLocked is CR 615.12 for a shield of
// this kind: applied to damage that can't be prevented, it prevents
// nothing and is not used up (CR 609.7b), and its additional effect still
// happens, with zero prevented.
//
// Caller must hold g.mu (write).
func (g *Game) preventionFollowUpForUnpreventableLocked(ev *ReplacementEvent, id ReplacementEffectID) {
	seq, mod, ok := decodeScopedReplacementID(id)
	if !ok {
		return
	}
	e, m, ok := g.scopedReplacementModLocked(seq, mod, ModPreventNextFromSource)
	if !ok {
		return
	}
	g.queuePreventionFollowUpLocked(e, m, ev, 0)
}

// --- choosing a source (CR 609.7a) ------------------------------------

// PendingChoiceChooseSource is "choose a source of damage" (CR 609.7a),
// asked as a prevention shield is created. Answered with
// {card_ids: [id]}; exactly one. It carries the card-set payload
// (ChooseCards, ChooseMin, ChooseMax), so the projection, the
// enumerator's acceptance check and the client's card grid are the
// shared ones.
//
// The candidates are public by construction — permanents, spells, cards
// in the command zone and cards in graveyards and exile that something
// still refers to — so nothing about the prompt is redacted. They are
// not re-checked against a zone on the answer: CR 609.7a lets a player
// choose an object that has left the zone it was in.
const PendingChoiceChooseSource PendingChoiceKind = "choose_source"

// ChooseSourcePrompt is the queue-side description of a choose_source.
type ChooseSourcePrompt struct {
	// Chooser chooses. Required.
	Chooser uuid.UUID
	// Source is the card asking.
	Source uuid.UUID
	// Question is the prompt's header.
	Question string
	// Queries narrows the candidates to the sources the card names ("a
	// red source of your choice"). Empty is any source.
	Queries []PermanentQuery
	// Controller narrows the candidates to the sources that player
	// controls (ADR 0108 §3: Desperate Gambit's "choose a source you
	// control"), read as each candidate is offered: a permanent's or a
	// spell's controller, a departed permanent's as it last existed, and
	// for a card that has no controller — one in the command zone, a
	// graveyard or exile — its owner (CR 108.4a). uuid.Nil is anyone's.
	Controller uuid.UUID
	// Then is handed the chosen source, or the zero ref when nothing
	// could be chosen (no legal source, or a chooser who has left).
	// Runs with g.mu held.
	Then func(g *Game, source ObjectRef, zone ZoneKind) error
}

// ChooseDamageSourceThenForEffect asks the chooser to choose a source and
// runs Then with it. Then runs even when no prompt could go up — no
// legal source, or a chooser who has left the game — with the zero ref,
// so the rest of the card is never stranded (#544). Reports whether a
// prompt was queued.
//
// Caller must hold g.mu in write mode (resolution frame).
func (g *Game) ChooseDamageSourceThenForEffect(p ChooseSourcePrompt) (bool, error) {
	cands := g.damageSourceCandidatesLocked(p.Queries, p.Controller)
	then := p.Then
	if who := g.playerByIDLocked(p.Chooser); who == nil || who.Eliminated || len(cands) == 0 {
		if then == nil {
			return false, nil
		}
		return false, then(g, ObjectRef{}, "")
	}
	question := p.Question
	if question == "" {
		question = "Choose a source of damage"
	}
	g.QueueChoiceForEffect(PendingChoice{
		Kind:        PendingChoiceChooseSource,
		Chooser:     p.Chooser,
		FromPlayer:  p.Chooser,
		Count:       1,
		Source:      p.Source,
		Reason:      question,
		ChooseCards: cands,
		ChooseMin:   1,
		ChooseMax:   1,
		chooseCardsResume: &chooseCardsFrame{
			then: chooseSourceThen(p.Chooser, p.Source, then),
		},
	})
	return true, nil
}

// chooseSourceThen pins the answer as it arrives — the source is the
// object it is NOW (CR 609.7a: "chosen when the effect is created") —
// and hands it on. A package-level constructor capturing scalars and the
// card's own continuation, the StackItem.Effect contract.
func chooseSourceThen(chooser, source uuid.UUID, then func(*Game, ObjectRef, ZoneKind) error) func(*Game, []uuid.UUID) error {
	return func(g *Game, picked []uuid.UUID) error {
		g.emitCardsChosenLocked(chooser, source, picked)
		var ref ObjectRef
		var zone ZoneKind
		if len(picked) == 1 {
			if r, z, ok := g.DamageSourceRefLocked(picked[0]); ok {
				ref, zone = r, z
			}
		}
		if then == nil {
			return nil
		}
		return then(g, ref, zone)
	}
}

// ResolveChooseSource answers a PendingChoiceChooseSource.
//
// Caller must NOT hold g.mu.
func (g *Game) ResolveChooseSource(choiceID, chooserID uuid.UUID, picks []uuid.UUID) error {
	return g.resolveCardSetPick(PendingChoiceChooseSource, choiceID, chooserID, picks)
}

// DamageSourceCandidatesLocked lists every source CR 609.7a lets a player
// choose that matches one of `qs` (all of them when `qs` is empty), each
// once, in this order:
//
//  1. permanents on the battlefield;
//  2. spells on the stack;
//  3. face-up objects in each command zone;
//  4. objects referred to by an item on the stack (its source and its
//     targets), by a scoped replacement or prevention effect waiting to
//     apply (its source, its affected objects and the objects its mods
//     name) or by a delayed trigger waiting to trigger (its source and
//     its cards) — wherever they are now, so long as the zone is public.
//     A card in a hand or a library is a new object nobody can see, and
//     is never offered.
//
// The properties are read off the battlefield's effective
// characteristics, off a spell or command-zone card as it is, and off a
// departed permanent's last-known information.
//
// Caller must hold g.mu (write: the layers are caught up first).
func (g *Game) DamageSourceCandidatesLocked(qs []PermanentQuery) []uuid.UUID {
	return g.damageSourceCandidatesLocked(qs, uuid.Nil)
}

// damageSourceCandidatesLocked is DamageSourceCandidatesLocked narrowed,
// when `controller` is set, to the sources that player controls
// (ChooseSourcePrompt.Controller).
//
// Caller must hold g.mu (write).
func (g *Game) damageSourceCandidatesLocked(qs []PermanentQuery, controller uuid.UUID) []uuid.UUID {
	g.RecomputeLayersIfStaleLocked()
	seen := map[uuid.UUID]bool{}
	var out []uuid.UUID
	add := func(id uuid.UUID, ok bool) {
		if id == uuid.Nil || seen[id] {
			return
		}
		seen[id] = true
		if ok {
			out = append(out, id)
		}
	}
	matches := func(ch *Characteristic) bool {
		return len(qs) == 0 || queriesMatchCharacteristic(qs, ch)
	}
	if g.Battlefield != nil {
		for i := range g.Battlefield.Cards {
			c := &g.Battlefield.Cards[i]
			ok := len(qs) == 0
			for _, q := range qs {
				ok = ok || q.matchesLocked(g, c)
			}
			add(c.InstanceID, ok && (controller == uuid.Nil || c.Controller == controller))
		}
	}
	if g.Stack != nil {
		for i := range g.Stack.Cards {
			c := &g.Stack.Cards[i]
			if item := g.StackMeta[c.InstanceID]; item != nil && item.Kind != StackItemSpell {
				continue
			}
			ch := SourceCharacteristics(c)
			add(c.InstanceID, matches(ch) && (controller == uuid.Nil || ch.Controller == controller))
		}
	}
	for _, p := range g.Seats {
		if p == nil || p.Command == nil {
			continue
		}
		for i := range p.Command.Cards {
			c := &p.Command.Cards[i]
			if c.FaceDown {
				continue
			}
			// CR 108.4a: a command-zone card has no controller; its
			// owner answers "a source you control".
			add(c.InstanceID, matches(SourceCharacteristics(c)) && (controller == uuid.Nil || p.ID == controller))
		}
	}
	for _, id := range g.referredToObjectsLocked() {
		if seen[id] {
			continue
		}
		ch, ok := g.referredSourceCharacteristicsLocked(id)
		add(id, ok && matches(ch) && g.referredSourceControlledByLocked(id, ch, controller))
	}
	return out
}

// referredToObjectsLocked is CR 609.7a's "any object referred to by" list,
// in a stable order: the stack items (top first — a spell's card and an
// ability's synthetic ID both key StackMeta, ordered by Seq), then the
// scoped replacement records, then the delayed triggers.
//
// Caller must hold g.mu.
func (g *Game) referredToObjectsLocked() []uuid.UUID {
	var out []uuid.UUID
	items := make([]*StackItem, 0, len(g.StackMeta))
	for _, item := range g.StackMeta {
		if item != nil {
			items = append(items, item)
		}
	}
	slices.SortFunc(items, func(a, b *StackItem) int { return cmpSeqDesc(a.Seq, b.Seq) })
	for _, item := range items {
		out = append(out, item.SourceCardID)
		for _, t := range item.Targets {
			if t.Kind == TargetCard {
				out = append(out, t.ID)
			}
		}
	}
	for i := range g.ScopedEffects {
		e := &g.ScopedEffects[i]
		replacement := false
		for _, m := range e.Mods {
			if modKinds[m.Kind].reader != readerReplacement {
				continue
			}
			replacement = true
			for _, o := range m.Objects {
				out = append(out, o.ID)
			}
		}
		if !replacement {
			continue
		}
		out = append(out, e.Source.ID)
		for _, a := range e.Affected {
			out = append(out, a.ID)
		}
	}
	for _, d := range g.DelayedTriggers {
		if d == nil {
			continue
		}
		out = append(out, d.SourceCardID)
		out = append(out, d.Cards...)
	}
	return out
}

// referredSourceControlledByLocked is the controller filter for a
// referred-to object: a permanent's or a spell's controller, a departed
// permanent's as it last existed (its last-known information), and for a
// card in a graveyard or exile, which nobody controls, its owner
// (CR 108.4a). True for every object when `controller` is unset.
//
// Caller must hold g.mu.
func (g *Game) referredSourceControlledByLocked(id uuid.UUID, ch *Characteristic, controller uuid.UUID) bool {
	if controller == uuid.Nil {
		return true
	}
	z := g.findCardZoneLocked(id)
	if z == nil {
		return false
	}
	switch z.Kind {
	case ZoneBattlefield, ZoneStack:
		return ch != nil && ch.Controller == controller
	}
	if _, departed := g.departedDamageSourceLocked(id, nil); departed && ch != nil && ch.Controller != uuid.Nil {
		return ch.Controller == controller
	}
	c, ok := g.LookupCardForEffect(id)
	return ok && c.Owner == controller
}

// cmpSeqDesc orders stack items newest (top) first.
func cmpSeqDesc[T int | int64 | uint64](a, b T) int {
	switch {
	case a > b:
		return -1
	case a < b:
		return 1
	}
	return 0
}

// referredSourceCharacteristicsLocked is the characteristics a referred-to
// object is judged by, and whether it may be offered at all: a public
// zone only. A card that left the battlefield and has not moved since is
// judged as it last existed there (CR 608.2h).
//
// Caller must hold g.mu.
func (g *Game) referredSourceCharacteristicsLocked(id uuid.UUID) (*Characteristic, bool) {
	z := g.findCardZoneLocked(id)
	if z == nil {
		return nil, false
	}
	switch z.Kind {
	case ZoneHand, ZoneLibrary:
		return nil, false
	}
	if z.Kind != ZoneBattlefield {
		if rec, ok := g.departedDamageSourceLocked(id, nil); ok {
			return lastKnownSourceCharacteristics(rec), true
		}
	}
	c, ok := g.LookupCardForEffect(id)
	if !ok || c.FaceDown {
		return nil, false
	}
	return SourceCharacteristics(&c), true
}
