import json,sys
d=json.load(open('comments.json'))
def build(num):
    v=d[num]
    L=[]
    L.append("## Re-triage against today's engine — the ready group is larger than this issue says")
    L.append("")
    L.append(f"**{v['ready']} → {v['ready']+v['total_freed']} cards need no new machinery.**")
    L.append("")
    L.append("The roadmap freezes the batch-01 detector set across all three ranking")
    L.append("passes on purpose, so the \"ready today\" counts stay comparable batch to")
    L.append("batch. The cost, which the roadmap states, is that the detectors go stale")
    L.append("as primitives land — and five of the blocker groups below have since")
    L.append("shipped in full. Their cards are writable now.")
    L.append("")
    L.append("Nothing was re-detected for this comment: the groups and the card lists")
    L.append("are this issue's own triage, re-sorted by what is on `develop` today.")
    L.append("")
    L.append("### Now unblocked — move these into the \"no new machinery\" group")
    L.append("")
    for h,c,why,cards in v['freed']:
        L.append(f"**{h} — {c} card{'s' if c!=1 else ''}** — shipped as {why}")
        L.append("")
        L.append("> " + " · ".join(cards))
        L.append("")
    if v['partial']:
        L.append("### Partly unblocked — check the card before filing it as blocked")
        L.append("")
        for h,c,why in v['partial']:
            L.append(f"- **{h} ({c} card{'s' if c!=1 else ''})** — {why}")
        L.append("")
    L.append("### Worth knowing before working this batch")
    L.append("")
    L.append("- The roadmap's own warning applies with full force: *re-check the triage")
    L.append("  before working a batch, because the blockers move faster than the issues do.*")
    L.append("- **Cost modification (#93) is the one the roadmap's stale-detector note misses.**")
    L.append("  It is the #1 blocker in all three ranking tables and it closed 2026-09-11,")
    L.append("  the same day batches 21–40 were ranked.")
    L.append("- A card in the freed list can still turn out to need a seam that does not")
    L.append("  exist. The detectors err toward optimism by design; the card-file author")
    L.append("  is the final arbiter, and a skip is a legitimate outcome — declare it here.")
    L.append("- The #259 rule still governs: a simplification that makes a card **weaker**")
    L.append("  than printed is acceptable and must be declared; **stronger** is not, and")
    L.append("  the card gets skipped instead.")
    L.append("")
    L.append("Measured across all 60 batches, **1,967 cards** sit in blocked groups whose")
    L.append("blocker has shipped — 658 on cost modification, 540 on until-end-of-turn,")
    L.append("332 on attachments, 234 on the mana pipeline and 203 on card types.")
    return "\n".join(L)
if __name__=='__main__':
    print(build(sys.argv[1]))
