package effects

import "github.com/krakenhavoc/cmd_and_ctrl/server/internal/game"

// Magus of the Moon — Creature — Human Wizard, {2}{R}, 2/2:
//
//	"Nonbasic lands are Mountains."
//
// Six words, one layer-4 static, and two rules that had to land
// before it could be catalogued at all. AGENTS.md §7 held it back
// through four batches for exactly those two.
//
// CR 305.7 — "an effect that sets a land's subtype to one or more of
// the basic land types" is not only a type change. The land loses the
// abilities generated by its own rules text and gains the basic land
// type's intrinsic mana ability. Both of those happen in LAYER 4,
// with the type change, which is what SetsBasicLandType declares:
//
//   - the subtype set replaces the land's own types, so a Bojuka Bog
//     is a Mountain and not a Mountain Swamp, and it taps for {R}
//     rather than {B}. The mana ability is not declared here — it is
//     derived from the effective subtypes by ManaAbilitiesForCard
//     (CR 305.6), which is also why it survives the removal in the
//     same breath.
//   - the ability loss is scoped to the LAND's own text. A Rancor on
//     an animated Dryad Arbor, or any ability another effect granted,
//     lands in layer 6 and is applied after this, so it survives.
//     That is CR 305.7's last sentence, and getting it right is what
//     #669 was for.
//
// CR 613.6 — the Magus's own ruling, 2021-03-19: "If Magus of the
// Moon loses its abilities, it continues to turn nonbasic lands into
// Mountains." A Darksteel Mutation or a Kenrith's Transformation on
// the Magus removes its abilities in layer 6, which is over an hour
// too late: the Mountains were made in layer 4 and the rules do not
// take them back. Until #669 the recompute dropped a silenced source
// from every layer and the lands reverted, which is the one thing
// this card must never do.
//
// Consequences at the table, all of them printed behaviour:
//
//   - BASIC lands are untouched. The supertype is the test (CR
//     205.4c), not the land type, so a Snow-Covered Mountain and a
//     basic Swamp both carry on.
//   - Everyone's lands, not just an opponent's. The Magus's
//     controller is playing a Mountain deck too.
//   - Urborg, Tomb of Yawgmoth is a nonbasic land, so the two settle
//     by timestamp (CR 613.7): the newer one wins. A Magus that
//     arrived after Urborg silences it in layer 4 and every nonbasic
//     is a Mountain; a Magus that was already there is itself turned
//     into a Swamp-in-addition by the newer Urborg, and stays a
//     Mountain Swamp. Neither is a CR 613.8 dependency — Urborg's
//     "each land" applies to the same set either way, and "add
//     Swamp" is the same instruction whatever the land already was.
//   - The Magus is a creature, so it dies to everything. That is the
//     whole reason it is a Magus and not a Blood Moon.
func init() {
	Register(Spec{
		OracleID:     "6800d01c-345d-4932-a2a4-8df0fb1902f2",
		Name:         "Magus of the Moon",
		Completeness: CompletenessFull,
		Static: []game.StaticAbility{
			SetsBasicLandType(nonbasicLand, nil, []string{"Mountain"}),
		},
	})
}

// nonbasicLand is CR 205.4c's "nonbasic land": a land without the
// basic SUPERTYPE. Effective on both halves, so a permanent another
// layer-4 effect made a land is one — and, being in the same layer,
// ordered against that effect by CR 613.8 rather than by timestamp.
func nonbasicLand(target *game.Card, _ *game.Game, _ *game.Card) bool {
	return target.IsLand() && !target.HasSupertype("basic")
}
